### ISSUE TITLE
Changing the method of checking if the location is not being faked.

### ISSUE THREAD

**Issue by MrPhenomenal3110** [skushagra/sst-app#11]
I have developer mode enabled in my device in order to reduce animations on my device an make them faster, but every time, in order to mark the attendance, I have to turn it off. So, I would suggest to use server-side validation instead of client-side validation, or some other techniques, which would not require to turn off the developer mode every time for marking attendance.

referenced file : ["/src/utils/checkValidity.js"](../blob/master/src/utils/checkValidity.js)

**Comment by skushagra** [comment]
We got this issue from many students, therefore our next build will have different checks to detect if attendance is being spoofed, and the requirement that the developer mode needs to be disabled to mark attendance will be removed.
