### ISSUE TITLE
Feat: Push Notification to mark attendance

### ISSUE THREAD

**Issue by Diwakar-Gupta** [skushagra/sst-app#2]
# NEED MORE VOLUNTEERS TO ADDRESS THIS ISSUE

Backend: https://github.com/Diwakar-Gupta/attendance-backend

## Problem Statement:
The current issue revolves around the need for a feature that reminds students to mark their attendance for class. We are actively seeking volunteers to contribute to the resolution of this matter.

## Proposed Solutions (not limited to):

1. **Push Notification Integration:** #4
   - Implement a solution that triggers push notifications from the backend.
   - Utilize Firebase to broadcast notifications across all mobile applications.

2. **Mobile Background Task:** #5
   - Develop a background task within the mobile application.
   - This task should fetch class timing details from the server and send notifications when the attendance window is open.

3. **Enhanced Notification Method:**
   - Building upon the background task concept, explore an option to play a loud notification noise on the user's phone to further capture attention during the attendance window.

## How to Contribute:
If you're interested in contributing to this issue, please:
- Fork the repository and create a new branch for your work.
- Submit a pull request with your proposed changes.

Let's work together to enhance the attendance marking process for students. Your contributions are highly valued!

**Comment by KeshavMakkad** [comment]
Please assign this to me

**Comment by narasimha-1511** [comment]
I ALSO WANT to work  ON THIS Issue??

**Comment by AbhinavGupta-de** [comment]
I want to work on this issue.

**Comment by arjun-kshirsagar** [comment]
Sir please assign it to me.

**Comment by ruthwikchikoti** [comment]
sir assign this to me

**Comment by naitikj9** [comment]
I want to work on this issue

**Comment by Diwakar-Gupta** [comment]
@naitikj9 @arjun-kshirsagar 
Please dont wait to get assigned to the issue you can start working on it, Once anyone get's the feature implemented i will notify it here.

**Comment by RiyaBhurse** [comment]
Sir ill work on this issue :)

**Comment by skushagra** [comment]
This feature has been added. Users will now recieve notificaitons which can be tiggered from the backend for a class or for any student indivisually.
